---
- hosts: all
  gather_facts: false
  tasks:
# write the attributes of the source node.
    - name: Output the source URI to json 
      copy: 
        dest: /home/ubuntu/intent/basic_three_node/result/source_api.json 
        content: "{'output_src_URI': '{{link_for_download}}'}"


    # - name: See what's in that linked text file
      # command: "python {{ text_file_artifact }}"
      # register: text_file_contents

    # - name: See what's in that linked text file
    #   # command: "cat {{ text_file_artifact }}"
    #   # register: text_file_contents

    # - name: Set text file attribute
      # set_stats:
      #   data:
      #     my_text_file_attribute: "{{ text_file_contents.stdout }}"

    - name: See what's in that linked JSON file
      command: "cat {{ json_file_artifact }}"
      register: json_file_contents

    - name: Set JSON file attribute
      set_stats:
        data:
          my_csv_file_attribute: "{{ json_file_contents.stdout }}"

