---
- hosts: all
  gather_facts: false
  tasks:

    - name: Output the source URI to json 
      copy: 
        dest: /home/ubuntu/intent/basic_three_node/result/sink_api.json
        content: "{'output_sink_URI': '{{link_for_download}}'}"

  # set the network attributes

    #   # command: "cat {{ text_file_artifact }}"
    #   # register: text_file_contents

    # - name: Set text file attribute
      # set_stats:
      #   data:
      #     my_text_file_attribute: "{{ text_file_contents.stdout }}"

    - name: See what's in that linked JSON file
      command: "cat {{ json_file_artifact }}"
      register: json_file_contents

    # - name: Set JSON file attribute
    #   set_stats:
    #     data:
    #       my_csv_file_attribute: "{{ json_file_contents.stdout }}"
    # - uri: 
    #     url: "{{ link_for_download }}"
    #     method: POST
    #     # return_content: yes
    #     # HEADER_Content-Type: "application/json"
    #     body: "{{ json_file_contents.stdout }}"
    #     body_format: json

